security:
    enable_authenticator_manager: true
    
    password_hashers:
        Ibexa\Core\MVC\Symfony\Security\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        ibexa:
            id: ibexa.security.user_provider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        ibexa_front:
            pattern: ^/
            user_checker: Ibexa\Core\MVC\Symfony\Security\UserChecker
            lazy: true
            entry_point: form_login
            ezpublish_http_basic:
                realm: Ibexa DXP
            
            provider: ibexa
            
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
                enable_csrf: true
            
            logout:
                path: logout
                target: /
    
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/login_check$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }
